apiVersion: v1
kind: Service
metadata:
  name: goapi
spec:
  type: NodePort
  selector:
    app: goapi  
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goapi-config
data:
  environment.env: |
    env=helm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
      - name: goapi
        image: guilhermeguth/goapi:master
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: go-volume
            mountPath: /app/config
            readOnly: true
      volumes:
        - name: go-volume
          configMap:
            name: goapi-config

